name: Publish axios client package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate .npmrc
        run: npm config set //registry.npmjs.org/:_authToken ${{secrets.NPM_AUTH_TOKEN}}

      - name: Install dependencies
        run: npm install

      - name: Publish client
        run: npm publish --access public
